main: baron.rol.main.TestClass
name: TestPlugin
version: 1.0
author: norab7
description: Test Plugin to get back into things
commands:
  mycommand:
    description: Test command to check it works
    usage: /testplugin01
#    permission: myplugin.mycommand
#    permission-message: You don't have the myplugin.mycommand permission.